### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.debug'

### ISSUE THREAD

**Issue by tangyubbb** [zhaojieting/Part_HOE#1]
python parthoe_test.py --cfg Config/parthoe.yaml
/home/huck/1a_tianji_code/src/Part_HOE/lib
Traceback (most recent call last):
  File "parthoe_test.py", line 29, in <module>
    from core.loss import JointsMSELoss
  File "/home/huck/1a_tianji_code/src/Part_HOE/lib/core/loss.py", line 9, in <module>
    from utils.debug import print_variable
ModuleNotFoundError: No module named 'utils.debug'

I cant find anything related to this issue, and this code isnot complete

**Comment by zhaojieting** [comment]
sorry for the trouble, i will fix it later this day.



---- Replied Message ----
| From | ***@***.***> |
| Date | 10/15/2024 17:10 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [zhaojieting/Part_HOE] ModuleNotFoundError: No module named 'utils.debug' (Issue #1) |

python parthoe_test.py --cfg Config/parthoe.yaml
/home/huck/1a_tianji_code/src/Part_HOE/lib
Traceback (most recent call last):
File "parthoe_test.py", line 29, in
from core.loss import JointsMSELoss
File "/home/huck/1a_tianji_code/src/Part_HOE/lib/core/loss.py", line 9, in
from utils.debug import print_variable
ModuleNotFoundError: No module named 'utils.debug'

I cant find anything related to this issue, and this code isnot complete

**Comment by zhaojieting** [comment]
The code can be run correctly now, but the test checkpoints isn't exactly same as the original version. 
I need to retrain it from scratch( may take 2 days), or you can retrain it on your computer.

**Comment by tangyubbb** [comment]
thank u, it helps me a lot

**Comment by zhaojieting** [comment]
I update the test weight just now, it's not the best version yet, but it is better than baseline. I will upload another best version for SOTA comparison later.

**Comment by zhaojieting** [comment]
remember do git pull, and download the test weight.
